#!/bin/bash

dataRoot="/home/data0/DICOM/"
helpMsg="   Must give at least 1 argument - the root name of data being written in "$dataRoot

if [ $# -eq 0 ] || [ $1 == "-h" ] || [ $1 == "--h" ] || [ $1 == "-help" ] || [ $1 == "--help" ]
then
   echo $helpMsg
   exit -1
fi

# plugout_drive -com "SETENV AFNI_REALTIME_Mask_Dset $maskset" -quit

Dimon -rt -quit -infile_prefix $dataRoot$1

